'use client';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {AppWindow} from 'lucide-react';
import {hideApps} from './hide-app-picker';
import {PictureControl} from './picture-control';
import type {Values} from './prototype-settings';
export function LauncherEditor({values:v,set,onBack,tell,backAsset}:{values:Values,set:(k:string,v:unknown)=>void,onBack:()=>void,tell:(s:string)=>void,backAsset:string}){
 const space=Number(v['launcher:space']??0),index=Number(v['launcher:selected']??-1),app=hideApps[index],prefix=`launcher:${space}:${index}`;
 const [name,rename]=useState(''),[picture,changePicture]=useState(''),[selecting,select]=useState(false),[query,search]=useState('');
 useEffect(()=>{rename(String(v[prefix+':name']||''));changePicture(String(v[prefix+':picture']||''))},[prefix,v[prefix+':name'],v[prefix+':picture']]);
 const confirm=()=>{if(!app){tell('请先选择应用');return}set(prefix+':name',name.trim());set(prefix+':picture',picture);tell(name.trim()?'修改已确认并保存到网页':'已恢复原名，图标按当前选择保存')};
 return <div className="revision-page launcher-page"><div className="launcher-scroll"><header className="launcher-header"><button aria-label="返回上一页" onClick={onBack}><img src={backAsset} alt=""/></button><h1>APP图标名称编辑</h1></header><p className="launcher-intro">先选择空间和应用，再修改名称或图片，点击确认修改。</p><label className="revision-field revision-select launcher-space"><span className="sr-only">选择空间</span><select aria-label="选择空间" value={space} onChange={e=>{set('launcher:space',Number(e.target.value));set('launcher:selected',-1)}}><option value={0}>机主</option><option value={999}>Mix11 · 空间 999</option></select></label><div className="revision-buttons launcher-select-button"><button onClick={()=>{search('');select(true)}}>选择应用</button></div><section className="revision-card launcher-edit-card"><PictureControl value={picture} onChange={changePicture} label="应用图标" blocked={!app} fallback={app?<AppWindow aria-hidden="true"/>:<img src="/native-assets/3ccf26198bb615b1.png" alt="尚未选择应用"/>} tell={tell}/><p className="launcher-selected">{app?(name.trim()||app.name):'尚未选择应用'}</p><input className="launcher-name" aria-label="自定义名称" placeholder="自定义名称，留空恢复原名" disabled={!app} value={name} onChange={e=>rename(e.target.value)}/><div className="revision-buttons"><button onClick={confirm}>确认修改</button><button onClick={()=>{if(!app){tell('请先选择应用');return}changePicture('');tell('已恢复原图标，点击确认修改保存')}}>恢复原图标</button></div></section><p className="launcher-intro">名称留空并确认修改，即恢复应用原名。网页仅预览，不会修改手机桌面。</p></div>{selecting&&createPortal(<div className="native-scrim"><section className="native-dialog launcher-app-dialog" role="dialog" aria-modal="true" aria-label="选择应用"><h2>选择应用</h2><input className="hide-search" aria-label="搜索应用名称或包名" placeholder="搜索应用名称或包名" value={query} onChange={e=>search(e.target.value)}/><div className="launcher-app-list">{hideApps.map((a,i)=>({...a,i})).filter(a=>(a.name+' '+a.pkg).toLowerCase().includes(query.trim().toLowerCase())).map(a=><button key={a.pkg} onClick={()=>{set('launcher:selected',a.i);select(false)}}><strong>{a.name}</strong><small>{a.pkg}</small></button>)}</div><p className="revision-note">应用列表为网页示例。</p><footer><button onClick={()=>select(false)}>取消</button></footer></section></div>,document.querySelector('.native-frame')!)}</div>;
}
