'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {ImagePlus} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
export function PictureControl({value,onChange,label,tell,blocked=false,fallback,buttons=false}:{value:string,onChange:(v:string)=>void,label:string,tell:(s:string)=>void,blocked?:boolean,fallback?:ReactNode,buttons?:boolean}){
 const input=useRef<HTMLInputElement>(null),[pending,setPending]=useState<{file:File,url:string}|null>(null),[zoom,setZoom]=useState(1),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{if(pending)URL.revokeObjectURL(pending.url)},[pending]);
 const choose=()=>blocked?tell('请先选择应用'):input.current?.click();
 async function accept(){if(!pending)return;setBusy(true);try{const bitmap=await createImageBitmap(pending.file),canvas=document.createElement('canvas');canvas.width=canvas.height=128;const size=Math.min(bitmap.width,bitmap.height)/zoom;canvas.getContext('2d')!.drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,128,128);bitmap.close();onChange(canvas.toDataURL('image/png'));setPending(null)}catch{tell('图片处理失败，请重新选择')}finally{setBusy(false)}}
 return <div className="picture-control"><button className="picture-preview" aria-label={'更换'+label} onClick={choose}>{value?<img src={value} alt={label}/>:fallback||<ImagePlus aria-hidden="true"/>}</button><input ref={input} type="file" hidden aria-label={'选择'+label+'文件'} accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10_000_000){tell('请选择 10 MB 以内的 PNG、JPG 或 WebP 图片');return}try{const bitmap=await createImageBitmap(file);bitmap.close();setZoom(1);setPending({file,url:URL.createObjectURL(file)})}catch{tell('无法读取这张图片，请重新选择')}}}/>{buttons?<div className="revision-buttons"><button onClick={choose}>选择图片</button><button onClick={()=>onChange('')}>恢复默认图片</button></div>:<p className="picture-hint">点击图标更换图片</p>}{pending&&createPortal(<div className="native-scrim"><section className="native-dialog picture-dialog" role="dialog" aria-modal="true" aria-label={'裁剪'+label}><h2>裁剪{label}</h2><div className="picture-crop"><img src={pending.url} alt="裁剪预览" style={{transform:`scale(${zoom})`}}/></div><label className="revision-range"><span>图片缩放<b>{zoom.toFixed(1)} 倍</b></span><Slider className="android-slider" aria-label="图片缩放" min={1} max={3} step={.1} value={[zoom]} onValueChange={n=>setZoom(Array.isArray(n)?n[0]:n)}/></label><footer><button disabled={busy} onClick={()=>setPending(null)}>取消</button><button disabled={busy} onClick={accept}>{busy?'处理中…':'使用此图片'}</button></footer></section></div>,document.querySelector('.native-frame')!)}</div>;
}
