'use client';
import {useEffect,useRef} from 'react';
export type Item={zone:string,order:number,size:number,on:boolean};
export type Status={enabled:boolean,items:Record<string,Item>,mode:number,nr:boolean,sr:boolean,layout:number[],custom:boolean,formats:string[],clockFlags:boolean[]};
type Node={id:string,zone:string,order:number,width:number,height:number,text:string,size:number};
export function StatusPreview({state,width,height,clockRows=2,notificationCount=0}:{state:Status,width:number,height:number,clockRows?:number,notificationCount?:number}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let live=true;document.fonts.ready.then(()=>{if(!live)return;const canvas=ref.current;if(!canvas)return;const c=canvas.getContext('2d');if(!c)return;canvas.width=width;canvas.height=height;
 c.fillStyle='#e7f3ff';c.beginPath();c.roundRect(0,0,width,height,39);c.fill();c.strokeStyle='#c7d9ea';c.lineWidth=1;c.beginPath();c.moveTo(0,height/2);c.lineTo(width,height/2);for(let i=1;i<3;i++){c.moveTo(width*i/3,0);c.lineTo(width*i/3,height)}c.stroke();
 const format=(s:string)=>s.replace(/HH|hh|mm|ss|MM|dd|II|I|E|N|e/g,x=>({HH:'08',hh:'08',mm:'50',ss:'30',MM:'09',dd:'06',II:'戊辰',I:'辰',E:'周日',N:'九',e:'初六'}[x]||x));
 const count=notificationCount||4,icons=Array.from({length:Math.max(1,Math.min(20,count))},()=> '●');
 const labels:Record<string,string>={clock:state.custom?state.formats.slice(0,clockRows).filter(Boolean).map(format).join('\n'):(state.clockFlags[0]?'08:50':'8:50')+(state.clockFlags[1]?':30':'')+(state.clockFlags[2]?(clockRows===2?'\n周日':' 周日'):''),notifications:state.nr?icons.slice(0,Math.ceil(count/2)).join(' ')+'\n'+icons.slice(Math.ceil(count/2)).join(' '):icons.join(' '),system_icons:state.sr?'◉ ◇\n◉ ◇':'◉ ◇ ◉ ◇',battery:'82%',cpu:'C:37°',gpu:'G:36°',battery_temp:'B:33°',current:'I:600mA',power:'P:2.4W',network:['','↑12K','↓36K','↑12K ↓36K','↑12K\n↓36K'][state.mode]};
 const nodes:Node[]=[];Object.entries(state.items).sort((a,b)=>a[1].order-b[1].order).forEach(([id,item])=>{if(!item.on)return;const size=Math.round(item.size*3.25);c.font=`${size}px Device`;const lines=labels[id].split('\n');const paired=id==='notifications'?state.nr:id==='system_icons'?state.sr:id==='network'&&state.mode===4;if(paired)lines.forEach((line,i)=>nodes.push({id:id+'#'+i,zone:item.zone[0]+(i+1),order:item.order,width:Math.max(1,c.measureText(line).width),height:size*1.15,text:line,size}));else nodes.push({id,zone:item.zone,order:item.order,width:Math.max(1,...lines.map(l=>c.measureText(l).width)),height:size*lines.length*1.15,text:labels[id],size})});
 const dp=(v:number)=>Math.round(v*3.25),barWidth=1216,barHeight=Math.max(107,dp(state.layout[0])),left=dp(4+state.layout[1]),right=dp(4+state.layout[2]),top=dp(state.layout[3]),bottom=dp(state.layout[4]),usableW=barWidth-left-right,usableH=barHeight-top-bottom,gap=Math.min(Math.max(0,dp(state.layout[5])),usableH/4),rowH=(usableH-gap)/2;
 const scale=Math.min(width/barWidth,(height-dp(8))/barHeight);c.save();c.translate((width-barWidth*scale)/2,(height-barHeight*scale)/2);c.scale(scale,scale);
 if(usableW>=3&&usableH>=2)for(let col=0;col<3;col++){const start=left+usableW*col/3,end=left+usableW*(col+1)/3,available=end-start,group=nodes.filter(n=>n.zone[0]==='LCR'[col]).sort((a,b)=>a.order-b.order),cursor=[0,0];let aligned=false;const both=group.some(n=>n.id==='notifications#0')&&group.some(n=>n.id==='notifications#1');const raw:{node:Node,x:number,w:number,h:number,s:number,row:number}[]=[];group.forEach(node=>{if(both&&!aligned&&node.id.startsWith('notifications#')){cursor[0]=cursor[1]=Math.max(...cursor);aligned=true}const span=node.zone[1]==='S',row=node.zone[1]==='2'?1:0,s=Math.min(1,(span?usableH:rowH)/node.height),w=node.width*s,h=node.height*s,x=span?Math.max(...cursor):cursor[row];raw.push({node,x,w,h,s,row:span?-1:row});if(span)cursor[0]=cursor[1]=x+w+2;else cursor[row]=x+w+2});const used=Math.max(0,Math.max(...cursor)-2),fit=used===0?1:Math.min(1,available/used),origin=col===2?end-used*fit:col===1?start+(available-used*fit)/2:start;raw.forEach(r=>{const h=r.h*fit,middle=top+usableH/2,y=r.row<0?middle-h/2:r.row===0?middle-gap/2-h:middle+gap/2;const lines=r.node.text.split('\n');c.font=`${r.node.size*r.s*fit}px Device`;c.fillStyle='#14233a';lines.forEach((line,i)=>c.fillText(line,origin+r.x*fit,y+(i+.82)*h/lines.length))})}c.restore();
 });return()=>{live=false}},[state,width,height,clockRows,notificationCount]);
 return <canvas ref={ref} style={{width,height}} aria-label="状态栏布局预览，左中右各分上下两排"/>;
}
