"""Exercise real startup jobs and binary gates with blocking service doubles; no ADB."""
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "android/app/src/main/java/ls/augment/com"
SOURCES = {
    "android/os/Looper.java": "package android.os; public final class Looper {private static final Looper M=new Looper();public static Looper getMainLooper(){return M;}}",
    "android/os/Handler.java": """package android.os;import java.util.concurrent.*;public final class Handler {private static final ExecutorService M=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"TestMain");t.setDaemon(true);return t;});public Handler(Looper l){}public boolean post(Runnable r){M.execute(r);return true;}}""",
    "android/os/SystemClock.java": "package android.os;public final class SystemClock {public static volatile long offset;public static long elapsedRealtime(){return System.nanoTime()/1000000+offset;}}",
    "android/os/Build.java": "package android.os;public final class Build {public static final class VERSION {public static int SDK_INT=36;}}",
    "android/os/PersistableBundle.java": """package android.os;import java.util.*;public final class PersistableBundle {private final Map<String,Object> m=new HashMap<>();public void putInt(String k,int v){m.put(k,v);}public int getInt(String k,int d){return m.containsKey(k)?(Integer)m.get(k):d;}public void putString(String k,String v){m.put(k,v);}public String getString(String k,String d){return m.containsKey(k)?(String)m.get(k):d;}}""",
    "android/util/Log.java": "package android.util;public final class Log {public static int w(String t,String m,Throwable e){return 0;}}",
    "android/net/Uri.java": "package android.net;public final class Uri {private final String p;public Uri(String p){this.p=p;}public String getSchemeSpecificPart(){return p;}}",
    "android/content/Intent.java": """package android.content;import android.net.Uri;public final class Intent {public static final String ACTION_BOOT_COMPLETED="boot",ACTION_LOCKED_BOOT_COMPLETED="locked",ACTION_MY_PACKAGE_REPLACED="self_replaced",ACTION_PACKAGE_ADDED="added",ACTION_PACKAGE_REMOVED="removed",ACTION_PACKAGE_REPLACED="replaced",ACTION_PACKAGE_CHANGED="changed";private final String action;private Uri data;public Intent(String a){action=a;}public String getAction(){return action;}public Intent setData(Uri u){data=u;return this;}public Uri getData(){return data;}}""",
    "android/content/IntentFilter.java": "package android.content;public final class IntentFilter {public void addAction(String a){}public void addDataScheme(String s){}}",
    "android/content/BroadcastReceiver.java": "package android.content;public abstract class BroadcastReceiver {public abstract void onReceive(Context c,Intent i);}",
    "android/content/ComponentName.java": "package android.content;public final class ComponentName {public final String name;public ComponentName(Context c,Class<?> k){name=k.getName();}}",
    "android/content/SharedPreferences.java": """package android.content;import java.util.*;import java.util.concurrent.*;public final class SharedPreferences {private final Map<String,Object> values=new ConcurrentHashMap<>();public String getString(String k,String d){return (String)values.getOrDefault(k,d);}public int getInt(String k,int d){return (Integer)values.getOrDefault(k,d);}public boolean getBoolean(String k,boolean d){return (Boolean)values.getOrDefault(k,d);}public Editor edit(){return new Editor();}public final class Editor {private final Map<String,Object> writes=new HashMap<>();public Editor putString(String k,String v){writes.put(k,v);return this;}public Editor putInt(String k,int v){writes.put(k,v);return this;}public Editor putBoolean(String k,boolean v){writes.put(k,v);return this;}public boolean commit(){values.putAll(writes);return true;}public void apply(){commit();}}}""",
    "android/content/pm/ApplicationInfo.java": "package android.content.pm;public final class ApplicationInfo {public String sourceDir;}",
    "android/content/pm/PackageInfo.java": "package android.content.pm;public final class PackageInfo {public ApplicationInfo applicationInfo;public long version;public long getLongVersionCode(){return version;}}",
    "android/content/pm/PackageManager.java": "package android.content.pm;public abstract class PackageManager {public abstract PackageInfo getPackageInfo(String p,int flags)throws Exception;}",
    "android/content/Context.java": """package android.content;import android.content.pm.*;import android.app.job.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;public class Context {public static final int MODE_PRIVATE=0,RECEIVER_NOT_EXPORTED=4;public String pkg="test.oem";public PackageManager pm;public final JobScheduler scheduler=new JobScheduler();public final List<BroadcastReceiver> receivers=new CopyOnWriteArrayList<>();private final Map<String,SharedPreferences> prefs=new ConcurrentHashMap<>();public final AtomicInteger prefReads=new AtomicInteger();public Context getApplicationContext(){return this;}public String getPackageName(){return pkg;}public PackageManager getPackageManager(){return pm;}public <T>T getSystemService(Class<T> c){return c.cast(scheduler);}public SharedPreferences getSharedPreferences(String n,int m){prefReads.incrementAndGet();return prefs.computeIfAbsent(n,k->new SharedPreferences());}public Intent registerReceiver(BroadcastReceiver r,IntentFilter f,int flags){receivers.add(r);return null;}public Intent registerReceiver(BroadcastReceiver r,IntentFilter f){return registerReceiver(r,f,0);}public void broadcast(){for(BroadcastReceiver r:receivers)r.onReceive(this,new Intent(Intent.ACTION_PACKAGE_REPLACED).setData(new android.net.Uri(pkg)));}}""",
    "android/app/job/JobInfo.java": """package android.app.job;import android.content.ComponentName;import android.os.PersistableBundle;public final class JobInfo {public static final int BACKOFF_POLICY_EXPONENTIAL=1;public final int id;public final boolean persisted;public final long backoff;private final PersistableBundle extras;private JobInfo(Builder b){id=b.id;extras=b.extras;persisted=b.persisted;backoff=b.backoff;}public PersistableBundle getExtras(){return extras;}public static final class Builder {final int id;PersistableBundle extras;boolean persisted;long backoff;public Builder(int id,ComponentName c){this.id=id;}public Builder setExtras(PersistableBundle e){extras=e;return this;}public Builder setPersisted(boolean p){persisted=p;return this;}public Builder setMinimumLatency(long m){return this;}public Builder setBackoffCriteria(long m,int p){backoff=m;return this;}public JobInfo build(){return new JobInfo(this);}}}""",
    "android/app/job/JobScheduler.java": """package android.app.job;import java.util.*;public final class JobScheduler {public static final int RESULT_SUCCESS=1;private final Map<Integer,JobInfo> jobs=new HashMap<>();public int schedules;public JobInfo getPendingJob(int id){return jobs.get(id);}public int schedule(JobInfo j){schedules++;jobs.put(j.id,j);return RESULT_SUCCESS;}}""",
    "android/app/job/JobParameters.java": "package android.app.job;import android.os.PersistableBundle;public final class JobParameters {private final PersistableBundle e;public JobParameters(JobInfo j){e=j.getExtras();}public PersistableBundle getExtras(){return e;}}",
    "android/app/job/JobService.java": """package android.app.job;import android.content.Context;import java.util.concurrent.*;public abstract class JobService extends Context {public static Context host;public final BlockingQueue<Finished> finishes=new LinkedBlockingQueue<>();public Context getApplicationContext(){return host;}public abstract boolean onStartJob(JobParameters p);public abstract boolean onStopJob(JobParameters p);public void jobFinished(JobParameters p,boolean r){finishes.add(new Finished(p,r));}public void onDestroy(){}public static final class Finished {public final JobParameters params;public final boolean retry;Finished(JobParameters p,boolean r){params=p;retry=r;}}}""",
    "ls/augment/com/BuildConfig.java": "package ls.augment.com;public final class BuildConfig {public static int VERSION_CODE=1;}",
    "ls/augment/com/ConfigSchema.java": "package ls.augment.com;public final class ConfigSchema {public static final String BATTERY_DISABLE_AGE_REDUCTION=\"battery\";}",
    "ls/augment/com/RootShell.java": """package ls.augment.com;final class RootShell {static final class Result {final int exitCode;Result(int c){exitCode=c;}boolean isSuccess(){return exitCode==0;}String publicError(){return "exit:"+exitCode;}}}""",
    "ls/augment/com/AppConfig.java": """package ls.augment.com;import android.content.Context;final class AppConfig {static final String DIAGNOSTICS="diag";AppConfig(Context c){}RootShell.Result mirrorAll(){return TestBootRecovery.mirror();}boolean getBoolean(String k){return true;}}""",
    "ls/augment/com/BatteryLifeControl.java": "package ls.augment.com;import android.content.Context;final class BatteryLifeControl {static RootShell.Result restore(Context c){return TestBootRecovery.battery();}}",
    "ls/augment/com/RootHideManager.java": """package ls.augment.com;import android.content.Context;final class RootHideManager {RootHideManager(Context c){}java.util.Set<String> targets(){return TestBootRecovery.hasTargets?java.util.Set.of("app"):java.util.Set.of();}OperationResult syncMirrors(){TestBootRecovery.io();TestBootRecovery.hiddenCalls.incrementAndGet();return new OperationResult(TestBootRecovery.hiddenSuccess);}static final class OperationResult {final boolean success;final String message="hidden_failed";OperationResult(boolean success){this.success=success;}}}""",
    "ls/augment/com/ScreenAutomation.java": "package ls.augment.com;import android.content.Context;final class ScreenAutomation {static void sync(Context c){TestBootRecovery.io();}}",
    "ls/augment/com/hook/FeatureSettings.java": "package ls.augment.com.hook;import android.content.Context;final class FeatureSettings {static volatile Context current;static Context from(Object o){return current;}}",
    "ls/augment/com/TestBootRecovery.java": r'''
package ls.augment.com;
import android.app.job.*;import android.content.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
public final class TestBootRecovery {
    static final AtomicInteger mirrorCalls=new AtomicInteger(),batteryCalls=new AtomicInteger(),hiddenCalls=new AtomicInteger(),wrongThread=new AtomicInteger();
    static volatile boolean hiddenSuccess=true,hasTargets=true;
    static volatile CountDownLatch gate,entered;static volatile int mirrorCode,batteryCode;
    static void check(boolean ok,String m){if(!ok)throw new AssertionError(m);}
    public static void io(){if(!Thread.currentThread().getName().equals("LSA-BootRecovery"))wrongThread.incrementAndGet();}
    static RootShell.Result mirror(){io();mirrorCalls.incrementAndGet();CountDownLatch g=gate;if(g!=null){entered.countDown();try{g.await();}catch(InterruptedException e){Thread.currentThread().interrupt();return new RootShell.Result(130);}}return new RootShell.Result(mirrorCode);}
    static RootShell.Result battery(){io();batteryCalls.incrementAndGet();return new RootShell.Result(batteryCode);}
    static Context host(boolean granted){Context c=new Context();if(granted)c.getSharedPreferences(AppConfig.DIAGNOSTICS,0).edit().putString("root_last_state","GRANTED").commit();JobService.host=c;mirrorCalls.set(0);batteryCalls.set(0);hiddenCalls.set(0);mirrorCode=batteryCode=0;hiddenSuccess=true;hasTargets=true;gate=entered=null;return c;}
    static JobParameters params(Context c,boolean upgrade){check(BootJobService.schedule(c,upgrade),"schedule failed");return new JobParameters(c.scheduler.getPendingJob(BootJobService.JOB_ID));}
    static JobService.Finished finish(BootJobService s)throws Exception{JobService.Finished f=s.finishes.poll(3,TimeUnit.SECONDS);check(f!=null,"job did not finish");return f;}
    public static void main(String[] args)throws Exception {
        Context c=host(true);BootReceiver receiver=new BootReceiver();int reads=c.prefReads.get();
        receiver.onReceive(c,new Intent("untrusted"));receiver.onReceive(c,new Intent(Intent.ACTION_LOCKED_BOOT_COMPLETED));check(c.scheduler.schedules==0,"unexpected action scheduled work");
        receiver.onReceive(c,new Intent(Intent.ACTION_BOOT_COMPLETED));JobInfo boot=c.scheduler.getPendingJob(BootJobService.JOB_ID);check(boot.getExtras().getInt("work",0)==5,"ordinary boot mirrors unnecessarily or lost hidden sync");
        receiver.onReceive(c,new Intent(Intent.ACTION_MY_PACKAGE_REPLACED));JobInfo upgraded=c.scheduler.getPendingJob(BootJobService.JOB_ID);check(upgraded.getExtras().getInt("work",0)==7,"upgrade lost restore/mirror/hidden work");
        receiver.onReceive(c,new Intent(Intent.ACTION_MY_PACKAGE_REPLACED));check(c.scheduler.schedules==2,"duplicate upgrade replaced an adequate job");check(c.prefReads.get()==reads,"receiver accessed preferences");check(upgraded.persisted&&upgraded.backoff==30000,"job persistence/backoff missing");
        BootJobService service=new BootJobService();gate=new CountDownLatch(1);entered=new CountDownLatch(1);JobParameters p=new JobParameters(upgraded);long start=System.nanoTime();check(service.onStartJob(p),"job did not stay alive");check(System.nanoTime()-start<TimeUnit.MILLISECONDS.toNanos(200),"onStartJob waited for Root");check(entered.await(2,TimeUnit.SECONDS),"worker did not enter mirror");check(service.finishes.isEmpty(),"finished while Root blocked");
        batteryCode=1;gate.countDown();check(finish(service).retry,"transient battery failure not retried");gate=null;batteryCode=0;service.onStartJob(new JobParameters(upgraded));check(!finish(service).retry,"success requested retry");check(mirrorCalls.get()==1&&batteryCalls.get()==2,"completed mirror not checkpointed");service.onDestroy();
        c=host(false);service=new BootJobService();service.onStartJob(params(c,true));check(!finish(service).retry,"Root-not-granted job kept retrying");check(mirrorCalls.get()==1&&batteryCalls.get()==0,"framework sync was gated on Root or requested Root");service.onDestroy();
        c=host(false);hasTargets=false;service=new BootJobService();service.onStartJob(params(c,false));check(!finish(service).retry&&hiddenCalls.get()==0&&batteryCalls.get()==0,"boot must not query independent Root state without authorization");service.onDestroy();
        c=host(true);service=new BootJobService();check(BootJobService.scheduleHiddenRefresh(c),"hidden-only schedule failed");p=new JobParameters(c.scheduler.getPendingJob(BootJobService.JOB_ID));check(p.getExtras().getInt("work",0)==4,"hidden-only request scheduled unrelated work");service.onStartJob(p);check(!finish(service).retry&&hiddenCalls.get()==1&&batteryCalls.get()==0&&mirrorCalls.get()==0,"hidden-only request performed unrelated Root or framework work");service.onDestroy();
        c=host(true);service=new BootJobService();p=params(c,true);mirrorCode=1;hiddenSuccess=false;service.onStartJob(p);check(finish(service).retry&&batteryCalls.get()==1&&hiddenCalls.get()==1,"failed framework blocked independent device recovery");mirrorCode=0;hiddenSuccess=true;service.onStartJob(p);check(!finish(service).retry&&batteryCalls.get()==1&&mirrorCalls.get()==2&&hiddenCalls.get()==2,"independent completed stage not checkpointed");service.onDestroy();
        c=host(true);service=new BootJobService();p=params(c,true);mirrorCode=1;service.onStartJob(p);check(finish(service).retry,"merge baseline not pending");check(BootJobService.scheduleHiddenRefresh(c),"fresh hidden request failed");mirrorCode=0;service.onStartJob(new JobParameters(c.scheduler.getPendingJob(BootJobService.JOB_ID)));check(!finish(service).retry&&hiddenCalls.get()==2&&batteryCalls.get()==1&&mirrorCalls.get()==2,"fresh hidden refresh reused its old checkpoint or repeated completed battery work");service.onDestroy();
        c=host(true);service=new BootJobService();p=params(c,true);mirrorCode=1;service.onStartJob(p);check(finish(service).retry,"reboot baseline not pending");mirrorCode=0;service.onStartJob(params(c,false));check(!finish(service).retry&&batteryCalls.get()==2&&hiddenCalls.get()==2,"new boot reused previous-boot device recovery checkpoints");service.onDestroy();
        c=host(true);service=new BootJobService();p=params(c,true);mirrorCode=1;batteryCode=40;service.onStartJob(p);check(finish(service).retry&&hiddenCalls.get()==1,"terminal battery failure suppressed other stages");mirrorCode=0;service.onStartJob(p);check(!finish(service).retry&&batteryCalls.get()==1&&hiddenCalls.get()==1,"terminal battery stage repeated on framework retry");service.onDestroy();
        c=host(true);service=new BootJobService();p=params(c,true);gate=new CountDownLatch(1);entered=new CountDownLatch(1);service.onStartJob(p);check(entered.await(2,TimeUnit.SECONDS),"cancel test did not start");start=System.nanoTime();check(service.onStopJob(p),"stopped job cannot resume");check(System.nanoTime()-start<TimeUnit.MILLISECONDS.toNanos(200),"onStopJob blocked");gate.countDown();gate=null;Thread.sleep(80);check(service.finishes.isEmpty(),"stopped invocation called jobFinished");service.onStartJob(new JobParameters(c.scheduler.getPendingJob(BootJobService.JOB_ID)));check(!finish(service).retry,"resumed job failed");check(batteryCalls.get()==1,"cancelled job continued to battery mutation");service.onDestroy();
        c=host(true);service=new BootJobService();p=params(c,false);batteryCode=1;for(int n=1;n<=3;n++){service.onStartJob(p);check(finish(service).retry==(n<3),"failure retry budget incorrect at "+n);}check(batteryCalls.get()==3,"unexpected number of failed operations");service.onDestroy();
        c=host(true);service=new BootJobService();batteryCode=40;service.onStartJob(params(c,false));check(!finish(service).retry,"unsupported battery policy retried");service.onDestroy();
        check(wrongThread.get()==0,"recovery I/O on callback thread");System.out.println("PASS boot jobs: dispatch-only receiver, merged persistent work, nonblocking start/stop, checkpoints, Root-independent framework sync, cancellation and bounded retries");
    }
}
''',
    "ls/augment/com/hook/TestOemBinaryAsync.java": r'''
package ls.augment.com.hook;
import android.content.*;import android.content.pm.*;import android.os.SystemClock;import java.nio.file.*;import java.security.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
public final class TestOemBinaryAsync {
    static final AtomicInteger calls=new AtomicInteger(),wrongThread=new AtomicInteger();static volatile CountDownLatch gate,entered;static volatile long version=7;static Path apk;static volatile boolean unavailable;
    static void check(boolean ok,String m){if(!ok)throw new AssertionError(m);}
    interface Condition{boolean get();}static void until(Condition c)throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(4);while(!c.get()){if(System.nanoTime()>end)throw new AssertionError("condition timed out");Thread.sleep(5);}}
    static String hash(byte[] bytes)throws Exception{StringBuilder s=new StringBuilder();for(byte b:MessageDigest.getInstance("SHA-256").digest(bytes))s.append(String.format("%02x",b&255));return s.toString();}
    static void block(){gate=new CountDownLatch(1);entered=new CountDownLatch(1);}
    public static void main(String[] args)throws Exception {
        byte[] good="verified OEM fixture".getBytes();apk=Files.createTempFile("lsa-oem-", ".apk");Files.write(apk,good);String expected=hash(good);Context c=new Context();
        c.pm=new PackageManager(){public PackageInfo getPackageInfo(String pkg,int flags)throws Exception{if(!Thread.currentThread().getName().equals("LSA-OemBinaryCheck"))wrongThread.incrementAndGet();calls.incrementAndGet();CountDownLatch g=gate;if(g!=null){entered.countDown();g.await();}if(unavailable)throw new Exception("blocked provider unavailable");PackageInfo i=new PackageInfo();i.version=version;i.applicationInfo=new ApplicationInfo();i.applicationInfo.sourceDir=apk.toString();return i;}};
        FeatureSettings.current=c;block();long start=System.nanoTime();OemBinaryGate.prepare(c.pkg,7,expected);check(System.nanoTime()-start<TimeUnit.MILLISECONDS.toNanos(200),"prepare blocked");check(entered.await(2,TimeUnit.SECONDS),"verification did not run");
        AtomicInteger callbacks=new AtomicInteger();Runnable listener=callbacks::incrementAndGet;OemBinaryGate.addListener(c,c.pkg,7,expected,listener);
        start=System.nanoTime();for(int n=0;n<10000;n++)check(!OemBinaryGate.matches(c,c.pkg,7,expected),"cold binary incorrectly allowed");check(System.nanoTime()-start<TimeUnit.MILLISECONDS.toNanos(500),"cold callers waited for PackageManager");check(calls.get()==1,"blocked lookup duplicated work");gate.countDown();gate=null;until(()->OemBinaryGate.matches(c,c.pkg,7,expected));until(()->callbacks.get()>0);
        int readCount=calls.get();for(int n=0;n<10000;n++)check(OemBinaryGate.matches(c,c.pkg,7,expected),"verified binary disabled");check(calls.get()==readCount,"cached hook queried PackageManager");
        CountDownLatch mismatch=new CountDownLatch(1);OemBinaryGate.addListener(c,c.pkg,7,"0".repeat(64),mismatch::countDown);check(mismatch.await(2,TimeUnit.SECONDS),"hash mismatch not checked");check(!OemBinaryGate.matches(c,c.pkg,7,"0".repeat(64)),"wrong SHA-256 allowed");
        CountDownLatch badVersion=new CountDownLatch(1);OemBinaryGate.addListener(c,c.pkg,8,expected,badVersion::countDown);check(badVersion.await(2,TimeUnit.SECONDS),"version mismatch not checked");check(!OemBinaryGate.matches(c,c.pkg,8,expected),"wrong version allowed");
        block();c.broadcast();check(entered.await(2,TimeUnit.SECONDS),"package change did not schedule verification");for(int n=0;n<1000;n++)check(!OemBinaryGate.matches(c,c.pkg,7,expected),"package change retained old allow verdict");Files.write(apk,"different unverified content".getBytes());final int changedBefore=callbacks.get();gate.countDown();gate=null;until(()->callbacks.get()>changedBefore);check(!OemBinaryGate.matches(c,c.pkg,7,expected),"changed APK passed binary gate");
        Files.write(apk,good);c.broadcast();until(()->OemBinaryGate.matches(c,c.pkg,7,expected));
        block();SystemClock.offset=61000;check(!OemBinaryGate.matches(c,c.pkg,7,expected),"expired verdict remained allowed");check(entered.await(2,TimeUnit.SECONDS),"expired verdict did not refresh");unavailable=true;int before=callbacks.get();gate.countDown();gate=null;final int oldCount=before;until(()->callbacks.get()>oldCount);check(!OemBinaryGate.matches(c,c.pkg,7,expected),"unavailable service opened gate");
        unavailable=false;SystemClock.offset=0;c.broadcast();until(()->OemBinaryGate.matches(c,c.pkg,7,expected));OemBinaryGate.removeListener(c.pkg,7,expected,listener);Thread.sleep(30);int stopped=callbacks.get();c.broadcast();Thread.sleep(100);check(callbacks.get()==stopped,"removed listener invoked");
        check(wrongThread.get()==0,"PackageManager called outside binary worker");Files.deleteIfExists(apk);System.out.println("PASS OEM gate: cold/cached hooks nonblocking, actual SHA/version mismatch rejection, package invalidation, expiry, service failure and listener cleanup");
    }
}
''',
}
for filename in ["BootReceiver.java", "BootJobService.java", "hook/OemBinaryGate.java"]:
    SOURCES[f"ls/augment/com/{filename}"] = (BASE / filename).read_text(encoding="utf-8")

with tempfile.TemporaryDirectory(prefix="lsa-boot-oem-test-") as temp:
    directory = Path(temp)
    files = []
    for name, source in SOURCES.items():
        path = directory / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
        files.append(str(path))
    subprocess.run(["javac", "-encoding", "UTF-8", "-d", temp, *files], check=True)
    for test in ["ls.augment.com.TestBootRecovery", "ls.augment.com.hook.TestOemBinaryAsync"]:
        subprocess.run(["java", "-cp", temp, test], check=True, timeout=30)
