"""Execute power-menu binding and all four click handlers with a fake PowerManager (no reboot)."""
from pathlib import Path
import ast,subprocess,tempfile
ROOT=Path(__file__).resolve().parents[1];SRC=ROOT/'android/app/src/main/java/ls/augment/com'
def literal_files(name):
 tree=ast.parse((ROOT/'tools'/name).read_text(encoding='utf-8'))
 return next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='files' for t in n.targets))
base=literal_files('test-back-gesture-runtime.py')
files={k:v for k,v in base.items() if k.startswith('io/') or k.endswith('/AugmentModule.java')}
files.update({
'android/content/Context.java':'package android.content;public class Context{public android.content.res.Resources getResources(){return new android.content.res.Resources();}public static final android.os.PowerManager POWER=new android.os.PowerManager();public <T>T getSystemService(Class<T> type){return type.cast(POWER);}}',
'android/os/PowerManager.java':'package android.os;public class PowerManager{public static boolean fail;public static final java.util.List<String> calls=java.util.Collections.synchronizedList(new java.util.ArrayList<>());public void reboot(String reason){calls.add(reason);if(fail)throw new SecurityException("denied");}}',
'android/util/DisplayMetrics.java':'package android.util;public class DisplayMetrics{public float density=1;}',
'android/content/res/Resources.java':'package android.content.res;public class Resources{public android.util.DisplayMetrics getDisplayMetrics(){return new android.util.DisplayMetrics();}}',
'android/graphics/Color.java':'package android.graphics;public class Color{public static final int WHITE=-1;}',
'android/graphics/drawable/GradientDrawable.java':'package android.graphics.drawable;public class GradientDrawable{public void setColor(int c){}public void setCornerRadius(float r){}}',
'android/view/View.java':'''package android.view;public class View{public Object tag;public boolean enabled=true;public ViewGroup parent;public ViewGroup.LayoutParams params=new ViewGroup.LayoutParams(100,100);public float x,y,translationY;public float getTranslationY(){return translationY;}public void setTranslationY(float n){translationY=n;}public OnClickListener click;
 public interface OnClickListener{void onClick(View v);}public interface OnLayoutChangeListener{void onLayoutChange(View v,int l,int t,int r,int b,int ol,int ot,int or,int ob);}
 public View(){}public View(android.content.Context c){}public android.content.Context getContext(){return new android.content.Context();}public android.content.res.Resources getResources(){return new android.content.res.Resources();}public int getWidth(){return 1080;}public int getHeight(){return 2400;}public void setTag(Object t){tag=t;}public void setEnabled(boolean on){enabled=on;}public void setOnClickListener(OnClickListener l){click=l;}public void performClick(){if(enabled&&click!=null)click.onClick(this);}public void setX(float v){x=v;}public void setY(float v){y=v;}public ViewGroup getParent(){return parent;}public ViewGroup.LayoutParams getLayoutParams(){return params;}public void requestLayout(){}public void getLocationOnScreen(int[] a){a[0]=0;a[1]=parent==null?0:Math.round(parent.translationY);}public boolean post(Runnable r){r.run();return true;}public boolean postDelayed(Runnable r,long n){return true;}
}''',
'android/view/ViewGroup.java':'''package android.view;import java.util.*;public class ViewGroup extends View{public List<View> children=new ArrayList<>();public List<OnLayoutChangeListener> listeners=new ArrayList<>();public ViewGroup(){}public ViewGroup(android.content.Context c){super(c);}public static class LayoutParams{public int width,height;public LayoutParams(int w,int h){width=w;height=h;}}public void addView(View v,LayoutParams p){children.add(v);v.parent=this;v.params=p;}public void removeView(View v){children.remove(v);v.parent=null;}public View findViewWithTag(Object t){for(View v:children)if(t.equals(v.tag))return v;return null;}public int getChildCount(){return children.size();}public View getChildAt(int i){return children.get(i);}public void addOnLayoutChangeListener(OnLayoutChangeListener l){listeners.add(l);}public void removeOnLayoutChangeListener(OnLayoutChangeListener l){listeners.remove(l);}}''',
'android/widget/FrameLayout.java':'package android.widget;public class FrameLayout extends android.view.ViewGroup{public FrameLayout(android.content.Context c){super(c);}public static class LayoutParams extends android.view.ViewGroup.LayoutParams{public LayoutParams(int w,int h){super(w,h);}}}',
'android/widget/LinearLayout.java':'package android.widget;public class LinearLayout extends android.view.ViewGroup{public static final int VERTICAL=1;public LinearLayout(android.content.Context c){super(c);}public void setOrientation(int n){}public static class LayoutParams extends android.view.ViewGroup.LayoutParams{public LayoutParams(int w,int h){super(w,h);}public LayoutParams(int w,int h,float f){super(w,h);}public void setMargins(int a,int b,int c,int d){}}}',
'android/widget/Button.java':'package android.widget;public class Button extends android.view.View{public String text;public Button(android.content.Context c){super(c);}public void setText(String s){text=s;}public void setAllCaps(boolean b){}public void setTextSize(float s){}public void setTextColor(int c){}public void setMinWidth(int n){}public void setMinimumWidth(int n){}public void setBackground(Object o){}}',
'android/widget/Toast.java':'package android.widget;public class Toast{public static final int LENGTH_LONG=1;public static volatile int shown;public static Toast makeText(android.content.Context c,String s,int n){return new Toast();}public void show(){shown++;}}',
'android/app/Dialog.java':'package android.app;public class Dialog{public boolean showing=true;public boolean isShowing(){return showing;}}',
'ls/augment/com/SystemUiOptions.java':'package ls.augment.com;public class SystemUiOptions{public static final String POWER_MODES="modes";}',
'ls/augment/com/hook/FeatureSettings.java':'package ls.augment.com.hook;public class FeatureSettings{static boolean on;static boolean enabled(android.content.Context c,String k){return on;}}',
'com/zte/feature/globalaction/MfvGlobalActionsDialog.java':'''package com.zte.feature.globalaction;public class MfvGlobalActionsDialog{public static class MFVActionsDialog extends android.app.Dialog{public android.view.ViewGroup mContentView=new android.view.ViewGroup();public android.view.View mResetContent=new android.view.View();public MFVActionsDialog(){((android.view.View)mResetContent).parent=new android.view.ViewGroup();}public int calls;public void initView(){calls++;}}}''',
'ls/augment/com/hook/TestPowerMenu.java':'''package ls.augment.com.hook;import android.view.*;import android.widget.*;import android.os.PowerManager;import com.zte.feature.globalaction.MfvGlobalActionsDialog.MFVActionsDialog;public class TestPowerMenu{
 static int checks;static void check(boolean ok,String s){checks++;if(!ok)throw new AssertionError(s);}static void init(MFVActionsDialog d)throws Throwable{AugmentModule.call(d,MFVActionsDialog.class,"initView",new Class[]{});}static ViewGroup rows(MFVActionsDialog d){return (ViewGroup)((ViewGroup)d.mContentView.getChildAt(0)).getChildAt(0);}static Button button(MFVActionsDialog d,int i){return (Button)((ViewGroup)rows(d).getChildAt(i/2)).getChildAt(i%2);}static void waitCalls(int n)throws Exception{long until=System.nanoTime()+1000000000L;while(PowerManager.calls.size()<n&&System.nanoTime()<until)Thread.sleep(1);check(PowerManager.calls.size()==n,"bounded fake reboot dispatch");}
 public static void main(String[] args)throws Throwable{AugmentModule m=new AugmentModule();AugmentModule.active=m;PowerMenuModesHook.install(m,TestPowerMenu.class.getClassLoader());MFVActionsDialog d=new MFVActionsDialog();init(d);check(d.calls==1&&d.mContentView.getChildCount()==0,"off retains native menu");
 FeatureSettings.on=true;init(d);init(d);check(d.mContentView.getChildCount()==1&&d.calls==3,"idempotent binding keeps native init");
 String[] labels={"Fastboot","Fastbootd","Recovery","9008"},reasons={"bootloader","fastboot","recovery","edl"};
 for(int i=0;i<4;i++){init(d);check(labels[i].equals(button(d,i).text),"exact label "+i);button(d,i).performClick();button(d,i).performClick();waitCalls(i+1);check(PowerManager.calls.get(i).equals(reasons[i]),"correct reboot reason "+i);}
 init(d);d.showing=false;button(d,0).performClick();check(PowerManager.calls.size()==4,"closed menu cannot reboot");d.showing=true;FeatureSettings.on=false;button(d,0).performClick();check(PowerManager.calls.size()==4,"stale button observes disabled setting");init(d);check(d.mContentView.getChildCount()==0&&d.mResetContent.parent.translationY==0,"disable removes actions and restores native row position");
 FeatureSettings.on=true;init(d);PowerManager.fail=true;button(d,3).performClick();waitCalls(5);long until=System.nanoTime()+1000000000L;while(Toast.shown==0&&System.nanoTime()<until)Thread.sleep(1);check(Toast.shown==1&&button(d,0).enabled,"failure reported and buttons reenabled");check(PowerManager.calls.size()==5,"failed reboot has no fallback to another mode");
 System.out.println("PASS power menu production binding/clicks: "+checks+" checks, fake provider only; no direct PowerManager call");}
}'''
})

# Inflate a representative OEM RelativeLayout subtree and run the production cloning factory.
files['android/util/TypedValue.java']='package android.util;public class TypedValue{public static final int COMPLEX_UNIT_PX=0;}'
files['android/util/SparseIntArray.java']='package android.util;public class SparseIntArray{java.util.Map<Integer,Integer> m=new java.util.HashMap<>();public void put(int a,int b){m.put(a,b);}public int get(int a){return m.getOrDefault(a,0);}}'
files['android/content/res/Resources.java']=files['android/content/res/Resources.java'].replace('public android.util', 'public int getIdentifier(String n,String t,String p){return 1;}public android.util')
files['android/graphics/drawable/Drawable.java']='package android.graphics.drawable;public class Drawable{public Object identity=new Object();public Drawable mutate(){return this;}public ConstantState getConstantState(){return new ConstantState(identity);}public static class ConstantState{Object identity;ConstantState(Object id){identity=id;}public Drawable newDrawable(android.content.res.Resources r){Drawable d=new Drawable();d.identity=identity;return d;}}}'
files['android/view/View.java']=files['android/view/View.java'].replace('public Object tag;', 'public static final int VISIBLE=0,NO_ID=-1;static int next=1000;public int id=-1,width=1080,height=2400;public String description;public android.graphics.drawable.Drawable background;public Object tag;').replace('return 1080;', 'return width;').replace('return 2400;', 'return height;').replace('public void setTag', 'public void setLayoutParams(ViewGroup.LayoutParams p){params=p;}public int getId(){return id;}public void setId(int n){id=n;}public static int generateViewId(){return next++;}public View findViewById(int n){return n==id?this:null;}public void setVisibility(int n){}public void setAlpha(float n){}public void setClickable(boolean b){}public void setFocusable(boolean b){}public void setContentDescription(String s){description=s;}public void setPadding(int a,int b,int c,int d){}public int getPaddingLeft(){return 0;}public int getPaddingTop(){return 0;}public int getPaddingRight(){return 0;}public int getPaddingBottom(){return 0;}public android.graphics.drawable.Drawable getBackground(){return background;}public void setBackground(android.graphics.drawable.Drawable d){background=d;}public void setTag')
files['android/view/ViewGroup.java']=files['android/view/ViewGroup.java'].replace('public void addView', 'public View findViewById(int n){if(id==n)return this;for(View v:children){View f=v.findViewById(n);if(f!=null)return f;}return null;}public void addView')
files['android/widget/FrameLayout.java']=files['android/widget/FrameLayout.java'].replace('public LayoutParams(int', 'public int leftMargin,topMargin;public LayoutParams(int')
files['android/widget/RelativeLayout.java']='package android.widget;public class RelativeLayout extends android.view.ViewGroup{public RelativeLayout(android.content.Context c){super(c);}public static class LayoutParams extends android.view.ViewGroup.LayoutParams{int[] rules=new int[20];public LayoutParams(int w,int h){super(w,h);}public int[] getRules(){return rules;}public void addRule(int i,int v){rules[i]=v;}public void removeRule(int i){rules[i]=0;}}}'
files['android/widget/ImageView.java']='package android.widget;public class ImageView extends android.view.View{public android.graphics.drawable.Drawable drawable=new android.graphics.drawable.Drawable();public Object tint=new Object(),scale=new Object();public ImageView(android.content.Context c){super(c);}public android.graphics.drawable.Drawable getDrawable(){return drawable;}public void setImageDrawable(android.graphics.drawable.Drawable d){drawable=d;}public Object getImageTintList(){return tint;}public void setImageTintList(Object o){tint=o;}public Object getScaleType(){return scale;}public void setScaleType(Object o){scale=o;}}'
files['android/widget/TextView.java']='package android.widget;public class TextView extends android.view.View{public String text="重启";float size=12,spacing=.1f;Object colors=new Object(),typeface=new Object();boolean padding;public TextView(android.content.Context c){super(c);}public void setText(String s){text=s;}public float getTextSize(){return size;}public void setTextSize(int unit,float n){size=n;}public Object getTextColors(){return colors;}public void setTextColor(Object o){colors=o;}public Object getTypeface(){return typeface;}public void setTypeface(Object o){typeface=o;}public boolean getIncludeFontPadding(){return padding;}public void setIncludeFontPadding(boolean b){padding=b;}public float getLetterSpacing(){return spacing;}public void setLetterSpacing(float n){spacing=n;}}'
files['android/view/LayoutInflater.java']='''package android.view;import android.widget.*;public class LayoutInflater{android.content.Context context;LayoutInflater(android.content.Context c){context=c;}public static LayoutInflater from(android.content.Context c){return new LayoutInflater(c);}public static RelativeLayout action(android.content.Context c){RelativeLayout a=new RelativeLayout(c);a.id=100;a.width=124;a.height=84;ImageView i=new ImageView(c);i.id=101;i.background=new android.graphics.drawable.Drawable();a.addView(i,new RelativeLayout.LayoutParams(60,60));TextView text=new TextView(c);text.id=102;RelativeLayout.LayoutParams p=new RelativeLayout.LayoutParams(124,15);p.addRule(3,101);p.addRule(13,-1);p.addRule(1,999);a.addView(text,p);return a;}public View inflate(int id,ViewGroup root,boolean attach){RelativeLayout result=new RelativeLayout(context);result.addView(action(context),new RelativeLayout.LayoutParams(-2,-2));return result;}}'''
files['com/zte/feature/globalaction/MfvGlobalActionsDialog.java']=files['com/zte/feature/globalaction/MfvGlobalActionsDialog.java'].replace('new android.view.View();','android.view.LayoutInflater.action(new android.content.Context());')
files['ls/augment/com/hook/TestPowerMenu.java']=files['ls/augment/com/hook/TestPowerMenu.java'].replace('return (ViewGroup)((ViewGroup)d.mContentView.getChildAt(0)).getChildAt(0);','return (ViewGroup)d.mContentView.getChildAt(0);').replace('static Button button(MFVActionsDialog d,int i){return (Button)((ViewGroup)rows(d).getChildAt(i/2)).getChildAt(i%2);}', 'static ViewGroup button(MFVActionsDialog d,int i){return (ViewGroup)rows(d).getChildAt(i);}').replace('button(d,i).text', 'NativePowerActionFactory.find(button(d,i),TextView.class).text').replace(' String[] labels=', '''
 ViewGroup action=button(d,0);ImageView original=NativePowerActionFactory.find(d.mResetContent,ImageView.class),copy=NativePowerActionFactory.find(action,ImageView.class);TextView sourceText=NativePowerActionFactory.find(d.mResetContent,TextView.class),copyText=NativePowerActionFactory.find(action,TextView.class);
 check(copy.params.width==60&&copy.params.height==60,"same OEM circle size");check(copy.getBackground()!=original.getBackground()&&copy.getBackground().identity==original.getBackground().identity,"independent native circular background resource");check(copy.getDrawable() instanceof PowerModeIconDrawable&&((PowerModeIconDrawable)copy.getDrawable()).mode.equals("Fastboot"),"mode-specific glyph replaces the OEM restart spinner");check(copy.getImageTintList()==original.getImageTintList(),"native theme tint");check(copyText.getTextSize()==sourceText.getTextSize()&&copyText.getTextColors()==sourceText.getTextColors()&&copyText.getTypeface()==sourceText.getTypeface(),"native label style");check(action.id!=100&&copy.id!=101&&copyText.id!=102,"cloned IDs do not collide with OEM animations");int[] rules=((RelativeLayout.LayoutParams)copyText.params).getRules();check(rules[3]==copy.id&&rules[13]==-1&&rules[1]==0,"relative references remap and external constraints cleared");check(action.params.width==124&&action.params.height==84,"native action dimensions");check(((FrameLayout.LayoutParams)button(d,2).params).topMargin==100,"portrait two rows");
 d.mContentView.width=2400;d.mContentView.height=1080;for(var listener:new java.util.ArrayList<>(d.mContentView.listeners))listener.onLayoutChange(d.mContentView,0,0,2400,1080,0,0,1080,2400);check(((FrameLayout.LayoutParams)button(d,3).params).leftMargin==124&&((FrameLayout.LayoutParams)button(d,3).params).topMargin==100,"landscape retains requested three rows");check(Math.abs(d.mResetContent.parent.translationY-(1080-284)/2f)<1&&Math.abs(rows(d).y-(1080-284)/2f-100)<1,"full three-row group vertically centered, native controls first");
 String[] labels=''')
files['ls/augment/com/hook/NativePowerActionFactory.java']=(SRC/'hook/NativePowerActionFactory.java').read_text(encoding='utf-8')
# Simulate the provider transport. Direct PowerManager.reboot must never be used.
files['android/os/Bundle.java']='package android.os;public class Bundle{public boolean ok;public String message="denied";public boolean getBoolean(String key,boolean fallback){return ok;}public String getString(String key,String fallback){return message;}}'
files['android/net/Uri.java']='package android.net;public class Uri{public String value;public static Uri parse(String s){Uri u=new Uri();u.value=s;return u;}}'
files['android/content/ContentResolver.java']='''package android.content;public class ContentResolver{
 public android.os.Bundle call(android.net.Uri uri,String method,String reason,android.os.Bundle extras){
 if(!"content://ls.augment.com.config".equals(uri.value)||!"power_mode_reboot".equals(method)||extras!=null)throw new AssertionError("invalid reboot bridge");
 android.os.PowerManager.calls.add(reason);android.os.Bundle b=new android.os.Bundle();b.ok=!android.os.PowerManager.fail;return b;
 }}'''
files['android/os/PowerManager.java']=files['android/os/PowerManager.java'].replace('calls.add(reason);if(fail)throw new SecurityException("denied");','throw new AssertionError("unprivileged reboot must never be called");')
files['android/content/Context.java']=files['android/content/Context.java'].replace('public class Context{','public class Context{public ContentResolver getContentResolver(){return new ContentResolver();}')
files['ls/augment/com/PowerModePolicy.java']=(SRC/'PowerModePolicy.java').read_text(encoding='utf-8')
files['android/view/View.java']=files['android/view/View.java'].replace('public void setVisibility(int n){}','public static final int INVISIBLE=4;public int visibility;public void setVisibility(int n){visibility=n;}')
files['com/zte/feature/globalaction/MfvGlobalActionsDialog.java']=files['com/zte/feature/globalaction/MfvGlobalActionsDialog.java'].replace('public int calls;', 'public void startSelectAnim(int n){}public void startActionAnim(int n){}public void startUnSelectedAnim(){}public void startUnVisiableAnim(){}public int calls;')
files['ls/augment/com/hook/TestPowerMenu.java']=files['ls/augment/com/hook/TestPowerMenu.java'].replace(' String[] labels=', ''' AugmentModule.call(d,MFVActionsDialog.class,"startSelectAnim",new Class[]{int.class},1);check(rows(d).visibility==View.INVISIBLE,"all advanced actions disappear on first OEM selection");
 AugmentModule.call(d,MFVActionsDialog.class,"startUnSelectedAnim",new Class[]{});check(rows(d).visibility==View.VISIBLE,"cancel restores advanced actions");
 String[] labels=''')
files['ls/augment/com/hook/PowerModeIconDrawable.java']='package ls.augment.com.hook;class PowerModeIconDrawable extends android.graphics.drawable.Drawable{final String mode;PowerModeIconDrawable(String value){mode=value;}}'
files['android/view/View.java']=files['android/view/View.java'].replace('public void setVisibility(int n)', 'public int clearCount;public void clearAnimation(){clearCount++;}public void setVisibility(int n)')
files['com/zte/feature/globalaction/GlobalAnimationUtils.java']='package com.zte.feature.globalaction;public class GlobalAnimationUtils{public int starts;public boolean nativeStarted;public void startVisibleAnim(android.view.View v,boolean show){if(!nativeStarted)throw new AssertionError("extras started before OEM");starts++;v.setVisibility(show?0:4);}}'
files['com/zte/feature/globalaction/MfvGlobalActionsDialog.java']=files['com/zte/feature/globalaction/MfvGlobalActionsDialog.java'].replace('public int calls;', 'public GlobalAnimationUtils mGlobalAnim=new GlobalAnimationUtils();public void startVisiableAnim(){mGlobalAnim.nativeStarted=true;}public int calls;').replace('public void startUnSelectedAnim(){}','public void startUnSelectedAnim(){mGlobalAnim.nativeStarted=true;}')
files['ls/augment/com/hook/TestPowerMenu.java']=files['ls/augment/com/hook/TestPowerMenu.java'].replace(' ViewGroup action=button(d,0);', ' check(rows(d).visibility==View.INVISIBLE&&d.mGlobalAnim.starts==0,"init never reveals extras before native entrance");AugmentModule.call(d,MFVActionsDialog.class,"startVisiableAnim",new Class[]{});check(rows(d).visibility==View.VISIBLE&&d.mGlobalAnim.starts==4,"four actions use native entrance during the same UI dispatch");ViewGroup action=button(d,0);').replace('check(labels[i].equals', 'check(((PowerModeIconDrawable)NativePowerActionFactory.find(button(d,i),ImageView.class).getDrawable()).mode.equals(labels[i]),"distinct glyph for each mode");check(labels[i].equals')
files['ls/augment/com/hook/PowerMenuModesHook.java']=(SRC/'hook/PowerMenuModesHook.java').read_text(encoding='utf-8')
with tempfile.TemporaryDirectory(prefix='lsa-power-modes-') as temp:
 sources=[]
 for name,source in files.items():
  path=Path(temp)/name;path.parent.mkdir(parents=True,exist_ok=True);path.write_text(source,encoding='utf-8');sources.append(str(path))
 subprocess.run(['javac','-encoding','UTF-8','-d',temp,*sources],check=True)
 subprocess.run(['java','-cp',temp,'ls.augment.com.hook.TestPowerMenu'],check=True)
